### ISSUE TITLE
Use maven to read and write pom.xml

### ISSUE THREAD

**Issue by pblanchardie** [jhipster/jhipster-lite#440] opened 2021-12-30 14:26 UTC
hand-made regex-based pom.xml generation code is error-prone.

why not using [Maven](https://maven.apache.org) itself for proper pom.xml management and validation?

at least we can rely on base objects like [Dependency](https://maven.apache.org/ref/3.5.2/maven-model/apidocs/org/apache/maven/model/Dependency.html) instead of creating custom ones, with strings

see
[Model](https://maven.apache.org/ref/3.5.2/maven-model/apidocs/org/apache/maven/model/Model.html)
[ModelBuildingRequest](https://maven.apache.org/ref/3.5.2/maven-model-builder/apidocs/org/apache/maven/model/building/ModelBuildingRequest.html)
[Maven Model Builder](https://maven.apache.org/ref/3.8.4/maven-model-builder/index.html)
etc.

[MavenXpp3Reader](https://maven.apache.org/ref/3.5.2/maven-model/apidocs/org/apache/maven/model/io/xpp3/MavenXpp3Reader.html) also allows reading an existing POM to extract some useful information.

could be nice to play with, will perhaps try on spare time after but will focus on features first ;)

I guess there are the same utilities for #408

**Comment by pascalgrimaud** [comment] 2021-12-30 18:21
Yes, we could use Maven to read in pom.xml but the problem is: it's a little bit slow :-D
When you generate a lof of files, calling Maven in each methods is not acceptable.
We could give a try but I'm afraid it won't work nice.

Instead, we could play with regexp:
- check if dependency is already here or not
- then, try to find needle and add dependency at this place
- if there is no needle, add it at the end of section:

```
  </dependency>
</dependencies>
```

**Comment by pblanchardie** [comment] 2021-12-30 19:04
Yes after writing this I also reminded that  simple text processing is much faster.
As long as our use cases stay simple we won't need such tooling.

**Comment by pascalgrimaud** [comment] 2022-02-15 22:07
Let's close this one as the current code works well

**Closed by pascalgrimaud** 2022-02-15 22:07 UTC
Labels: area: enhancement :wrench:, theme: maven
