### ISSUE TITLE
GraalVM Native Support is broken

### ISSUE THREAD

**Issue by msivade** [jhipster/jhipster-lite#5535] opened 2023-03-02 13:55 UTC
### How to reproduce

- Environment
```Version info: GraalVM 22.3.1 Java 17 CE
 Java version info: 17.0.6+10-jvmci-22.3-b13
 C compiler: gcc (linux, x86_64, 11.3.0)
 Garbage collector: Serial GC 
```

- Follow README GraalVM NativeSupport section :
   - `./mvnw spring-boot:build-image -Pnative`
   - `docker run -p 7471:7471 --rm docker.io/library/jhlite:0.28.1-SNAPSHOT`

- Fails to run the app on docker : 

```Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.pattern.parser.Compiler@e228e97 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.DateConverter] for keyword [d] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.DateConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@e228e97 - [d] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@56d56290 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LevelConverter] for keyword [p] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LevelConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@56d56290 - [p] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@f442a1d - Failed to instantiate converter class [ch.qos.logback.classic.pattern.ThreadConverter] for keyword [t] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.ThreadConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@f442a1d - [t] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@71a25531 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LoggerConverter] for keyword [logger] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LoggerConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@71a25531 - [logger] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@5e0043dd - Failed to instantiate converter class [ch.qos.logback.classic.pattern.MessageConverter] for keyword [m] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.MessageConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@5e0043dd - [m] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@5e0043dd - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LineSeparatorConverter] for keyword [n] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LineSeparatorConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@5e0043dd - [n] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.DateConverter] for keyword [d] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.DateConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [d] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LevelConverter] for keyword [p] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LevelConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [p] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.ThreadConverter] for keyword [t] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.ThreadConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [t] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LoggerConverter] for keyword [logger] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LoggerConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [logger] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.MessageConverter] for keyword [m] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.MessageConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [m] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - Failed to instantiate converter class [ch.qos.logback.classic.pattern.LineSeparatorConverter] for keyword [n] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.pattern.LineSeparatorConverter
ERROR in ch.qos.logback.core.pattern.parser.Compiler@79303280 - [n] is not a valid conversion word
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reportConfigurationErrorsIfNecessary(LogbackLoggingSystem.java:261)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initializeFromAotGeneratedArtifactsIfPossible(LogbackLoggingSystem.java:212)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:187)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base@17.0.5/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at tech.jhipster.lite.JHLiteApp.main(JHLiteApp.java:19)
%PARSER_ERROR[d] %PARSER_ERROR[p] 1 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]
...
```

### Hints for fixing issue 

- Adding native-maven-plugin fixed the issue and I could start docker container running JHipster Lite
```<!-- Plugin for GraalVM build in docker container and run native tests -->
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <!-- use the recommended JUnit Platform test listener mode -->
        <extensions>true</extensions>
        <configuration>
          <metadataRepository>
            <enabled>true</enabled>
          </metadataRepository>
          <requiredVersion>${maven-native-plugin.version}</requiredVersion>
          <buildArgs>
            <!-- build standalone image -->
            <buildArg>--no-fallback</buildArg>
            <!-- avoid errors of unresolved type during parsing -->
            <buildArg>--allow-incomplete-classpath</buildArg>
            <!-- allow HTTP and HTTPS -->
            <buildArg>-H:EnableURLProtocols=http,https</buildArg>
            <buildArg>--enable-all-security-services</buildArg>
            <!-- to be able to run native tests -->
            <buildArg>--static</buildArg>
            <buildArg>--initialize-at-build-time=io.cucumber.core,io.cucumber.gherkin,org.junit.jupiter.api,io.cucumber.junitxmlformatter,java.io.FileOutputStream</buildArg>
          </buildArgs>
        </configuration>
        <executions>
          <execution>
            <id>add-reachability-metadata</id>
            <goals>
              <goal>add-reachability-metadata</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

- Still has some issues with file descriptor in the image heap when running native tests `./mvnw test -PnativeTest`

 ```Error: Unsupported features in 3 methods
Detailed message:
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image runtime, and the files might not even be present anymore at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.io.FileDescriptor. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field java.io.FileOutputStream.fd of constant 
    java.io.FileOutputStream@5dcaa7f5: java.io.FileOutputStream@5dcaa7f5
  reading field sun.nio.cs.StreamEncoder.out of constant 
    sun.nio.cs.StreamEncoder@2415fcd9: sun.nio.cs.StreamEncoder@2415fcd9
  reading field java.io.OutputStreamWriter.se of constant 
    java.io.OutputStreamWriter@1401a5b7: java.io.OutputStreamWriter@1401a5b7
  reading field io.cucumber.junitxmlformatter.MessagesToJunitXmlWriter.out of constant 
    io.cucumber.junitxmlformatter.MessagesToJunitXmlWriter@29bebaaa: io.cucumber.junitxmlformatter.MessagesToJunitXmlWriter@29bebaaa
  reading field io.cucumber.core.plugin.JUnitFormatter.writer of constant 
    io.cucumber.core.plugin.JUnitFormatter@143033cb: io.cucumber.core.plugin.JUnitFormatter@143033cb
  indexing into array java.lang.Object[]@4039314a: [Ljava.lang.Object;@4039314a
  reading field java.util.ArrayList.elementData of constant 
    java.util.ArrayList@17317510: [io.cucumber.core.plugin.PrettyFormatter@5b962e9b, io.cucumber.core.plugin.JsonF...
  reading field io.cucumber.core.plugin.Plugins.plugins of constant 
    io.cucumber.core.plugin.Plugins@783fcc41: io.cucumber.core.plugin.Plugins@783fcc41
  reading field io.cucumber.junit.Cucumber.plugins of constant 
    io.cucumber.junit.Cucumber@1f5e4ec9: io.cucumber.junit.Cucumber@1f5e4ec9
  reading field org.junit.vintage.engine.descriptor.RunnerTestDescriptor.runner of constant 
    org.junit.vintage.engine.descriptor.RunnerTestDescriptor@2f0dbedf: RunnerTestDescriptor: [engine:junit-vintage]/[runner:tech.jhipster.lite.cucumber...
  reading field java.util.HashMap$Node.key of constant 
    java.util.LinkedHashMap$Entry@39da43c6: RunnerTestDescriptor: [engine:junit-vintage]/[runner:tech.jhipster.lite.cucumber...
  reading field java.util.LinkedHashMap.tail of constant 
    java.util.LinkedHashMap@13df2b53: {RunnerTestDescriptor: [engine:junit-vintage]/[runner:tech.jhipster.lite.cucumbe...
  reading field java.util.HashSet.map of constant 
    java.util.LinkedHashSet@7883a81d: [RunnerTestDescriptor: [engine:junit-vintage]/[runner:tech.jhipster.lite.cucumbe...
  reading field java.util.Collections$SynchronizedCollection.c of constant 
    java.util.Collections$SynchronizedSet@2e9622cc: [RunnerTestDescriptor: [engine:junit-vintage]/[runner:tech.jhipster.lite.cucumbe...
  reading field org.junit.platform.engine.support.descriptor.AbstractTestDescriptor.children of constant 
    org.junit.vintage.engine.descriptor.VintageEngineDescriptor@144d064a: VintageEngineDescriptor: [engine:junit-vintage]
  reading field java.util.HashMap$Node.value of constant 
    java.util.LinkedHashMap$Entry@55785a27: org.junit.vintage.engine.VintageTestEngine@32d8e58d=VintageEngineDescriptor: [en...
  reading field java.util.LinkedHashMap.tail of constant 
    java.util.LinkedHashMap@3a043b26: {org.junit.jupiter.engine.JupiterTestEngine@4bc39640=JupiterEngineDescriptor: [e...
  reading field java.util.Collections$UnmodifiableMap.m of constant 
    java.util.Collections$UnmodifiableMap@742529f: {org.junit.jupiter.engine.JupiterTestEngine@4bc39640=JupiterEngineDescriptor: [e...
  reading field org.junit.platform.launcher.core.LauncherDiscoveryResult.testEngineDescriptors of constant 
    org.junit.platform.launcher.core.LauncherDiscoveryResult@171925bb: org.junit.platform.launcher.core.LauncherDiscoveryResult@171925bb
  reading field org.junit.platform.launcher.core.InternalTestPlan.discoveryResult of constant 
    org.junit.platform.launcher.core.InternalTestPlan@3aa4fa7b: org.junit.platform.launcher.core.InternalTestPlan@3aa4fa7b
  scanning root org.junit.platform.launcher.core.InternalTestPlan@3aa4fa7b: org.junit.platform.launcher.core.InternalTestPlan@3aa4fa7b embedded in 
    org.graalvm.junit.platform.NativeImageJUnitLauncher.execute(NativeImageJUnitLauncher.java:74)
...
```
In this article, these errors seem tedious : [https://simply-how.com/fix-graalvm-native-image-compilation-issues](fix-graalvm-native-image-compilation-issues) 

- We could also investigate AOT following [[Springboot](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html)](Springboot documentation) as currently JHipster Lite does not allow AOT

-  Some steps described in this article could maybe help as well [https://blog.codecentric.de/spring-boot-graalvm](springboot-graalvm) even though this article is a little old

**Comment by pascalgrimaud** [comment] 2023-03-02 13:59
Thanks a lot for all these details, @msivade !

cc @atomfrede as you added the support, maybe you can have a look when you have time plz?

**Comment by atomfrede** [comment] 2023-03-02 14:22
Will have a look. It looks strange as we tried to customize very few things. @msivade did you try the native image (instead the docker container?)

**Comment by msivade** [comment] 2023-03-03 08:25
Yes I tried the native image and I could start the app without any issues.

As for the native tests, my bad, I thought we supported them as it was in the README.

Thanks a lot!

**Comment by atomfrede** [comment] 2023-03-03 08:35
So the issue is related to the native container image and the native tests, right? With regards to native tests I think we missed to exclude the tests for the container command. For the native executable the tests are skipped.

**Comment by msivade** [comment] 2023-03-03 08:52
yes exactly.

**Comment by atomfrede** [comment] 2023-03-06 06:11
I would suggest to close this and create a new ticket to track the native testing issue.

**Comment by pascalgrimaud** [comment] 2023-03-06 06:26
Ok @atomfrede : can you ?

**Closed** 2023-03-06 11:07 UTC
Labels: area: bug :bug:, generator: internal
